// app/layout.js

import { Geist, Geist_Mono } from "next/font/google";
import { StackProvider, StackTheme } from "@stackframe/stack";
import { stackServerApp } from "../stack";
import "./globals.css";             // Global styles
import Provider from "./provider";  // Your custom provider (must have "use client" if it uses browser APIs)

// Configure custom Google fonts
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});
const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// Default metadata (optional)
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    // Next.js server component by default
    <html lang="en" className={`${geistSans.variable} ${geistMono.variable}`}>
      <body className="antialiased">
        {/* Wrap your entire app in StackProvider, StackTheme, and your custom Provider */}
        <StackProvider app={stackServerApp}>
          <StackTheme>
            <Provider>{children}</Provider>
          </StackTheme>
        </StackProvider>
      </body>
    </html>
  );
}
